(()=>{
const vocabMeanings={expand:'拡大する',observe:'守る・順守する',review:'確認する・見直す',complimentary:'無料の',announce:'発表する',significantly:'大幅に・著しく',prompt:'迅速な',capacity:'能力・収容力',submit:'提出する',efficiency:'効率',located:'位置している',commission:'歩合・手数料',reimburse:'払い戻す',valid:'有効な',schedule:'予定',identify:'特定する',selection:'品揃え・選択肢',approval:'承認',qualified:'適任の・資格のある',interruption:'中断',comprehensive:'包括的な',proof:'証明',generate:'生み出す',mandatory:'必須の',accommodate:'収容する・対応する',reputation:'評判',arrive:'到着する',options:'選択肢',renovation:'改装',statement:'声明・発表'};
const phraseMeanings={'due to':'～が原因で','no later than':'遅くとも～までに','into effect':'発効して・実施されて','in charge of':'～を担当して','because of':'～のために・～が原因で','within':'～以内に','to hearing':'聞くことを（look forward to hearingで「連絡を楽しみにする」）','at':'～で（at short noticeで「急な通知で」）','with prior':'事前の～を得て','in case':'～の場合に備えて','on behalf of':'～を代表して・～に代わって','on':'～で（on a regular basisで「定期的に」）','in':'～の中で','to':'～に（be subject toで「～を受ける」）','of':'～の（free of chargeで「無料で」）','until':'～まで','under':'～の条件下で'};
const phraseDisplay={
'due to':'due to','no later than':'no later than','into effect':'go into effect','in charge of':'in charge of','because of':'because of','within':'within 30 days','to hearing':'look forward to hearing','at':'at short notice','with prior':'with prior approval','in case':'in case','on behalf of':'on behalf of','on':'on a regular basis','in':'in the process of / in advance','to':'be subject to','of':'free of charge','until':'until further notice','under':'under normal use'};
const jpDistractors=['延期する','購入する','提案する','配達する','無料の','承認','効率','評判','提出する','到着する','必須の','迅速な','中断','選択肢','改装','～に加えて','～の代わりに','～より前に','～にもかかわらず','～を担当して','～が原因で','遅くとも～までに','無料で','定期的に'];
const grammarMeta=[
['品詞','新しい会計システムは、以前のものよりはるかに効率的です。'],['時制','田中さんは2021年からこの会社で働いています。'],['受動態','すべての申請書は5月10日までに提出されなければなりません。'],['時制','マネージャーは、その報告書が正午までに準備できるか尋ねました。'],['接続詞','天候は悪かったものの、屋外イベントは予定どおり続行されました。'],['関係詞','窓の近くに机がある従業員がお手伝いできます。'],['時制','何かお手伝いが必要でしたら、フロントデスクにお電話ください。'],['品詞','そのプレゼンテーションは非常に有益だったので、数名の顧客がコピーを求めました。'],['主語と動詞の一致','2つの提案のどちらも、まだ承認されていません。'],['語法','少なくとも1週間前に予約することをお勧めします。'],['分詞','机の上に置かれている書類は受け取りの準備ができています。'],['前置詞','ブラウンさんは月次売上報告書の作成を担当しています。'],['語法','会社は西部地域の顧客に対応するため、2つ目のオフィスを開設しました。'],['接続詞','最終決定は予算が承認されるかどうかに左右されます。'],['品詞','このモデルは当店で最も信頼性の高いプリンターの一つです。'],['時制','私たちが到着した時には、会議はすでに始まっていました。'],['接続詞','元のレシートがあれば、商品を返品できます。'],['比較','新しいオフィスは古いオフィスの2倍の広さです。'],['分詞','その職に興味がある人は誰でもオンラインで応募してください。'],['語法','取締役は、修正された契約書を直ちに送付するよう求めました。'],['主語と動詞の一致','オンライン注文の数は今四半期に大幅に増加しました。'],['品詞','従業員は締め切りに間に合うよう効率的に働くことが推奨されています。'],['時制','基調講演者が到着し次第、会議が始まります。'],['関係詞','その機器は昨年購入されたもので、まだ保証期間内です。'],['語法','お客様から好意的なフィードバックをいただき、うれしく思いました。'],['前置詞','最終決定を下す前に考慮すべき要素がいくつかあります。'],['比較','荷物は当初の予定より早く到着するはずです。'],['語法','点検後に限り、その機械を再び使用できます。'],['語法','会社は注文増加に対応するため追加スタッフを雇いました。'],['語法','ご質問がありましたら、遠慮なくお問い合わせください。']];
const grammarStart=questions.findIndex(q=>q.c==='grammar');
questions.forEach((q,i)=>{if(q.c==='grammar'&&grammarMeta[i-grammarStart]){q.gc=grammarMeta[i-grammarStart][0];q.jp=grammarMeta[i-grammarStart][1];}});
function pickJapanese(correct,cat){const source=cat==='vocab'?Object.values(vocabMeanings):Object.values(phraseMeanings);const out=[correct];for(const x of [...source,...jpDistractors].sort(()=>Math.random()-.5)){if(!out.includes(x))out.push(x);if(out.length===4)break;}return out.sort(()=>Math.random()-.5)}
function fullSentence(q){return q.q.replace('_____',q.o[q.a]);}
function roughTranslation(q){const term=q.o[q.a];if(q.c==='vocab')return `例文の中では「${vocabMeanings[term]||term}」という意味で使われています。`;return `この例文では「${phraseDisplay[term]||term}」をひとかたまりで覚えるのがポイントです。`;}
window.renderQuestion=function(){locked=false;const q=pool[pos];if(!q){showHome();return}document.getElementById('qcat').textContent=q.c==='grammar'?'文法・'+(q.gc||'総合'):labels[q.c]+'問題';document.getElementById('qnum').textContent=(pos+1)+' / '+pool.length;const qt=document.getElementById('qtext');const box=document.getElementById('choices');box.innerHTML='';if(q.c==='vocab'||q.c==='phrase'){const term=q.o[q.a];qt.textContent=q.c==='vocab'?term:(phraseDisplay[term]||term);const correct=q.c==='vocab'?vocabMeanings[term]:phraseMeanings[term];q._jp=pickJapanese(correct,q.c);q._ja=q._jp.indexOf(correct);q._jp.forEach((x,i)=>{const b=document.createElement('button');b.className='choice';b.textContent=String.fromCharCode(65+i)+'. '+x;b.onclick=()=>answer(i,b);box.appendChild(b)});}else{qt.textContent=q.q;q.o.forEach((x,i)=>{const b=document.createElement('button');b.className='choice';b.textContent=String.fromCharCode(65+i)+'. '+x;b.onclick=()=>answer(i,b);box.appendChild(b)});}document.getElementById('explain').classList.add('hidden');document.getElementById('nextBtn').classList.add('hidden')};
window.answer=function(i,b){if(locked)return;locked=true;const q=pool[pos];const correctIndex=(q.c==='vocab'||q.c==='phrase')?q._ja:q.a;const buttons=[...document.querySelectorAll('.choice')];buttons[correctIndex].classList.add('correct');if(i!==correctIndex)b.classList.add('wrong');state.history[q.i]=i===correctIndex;save();const e=document.getElementById('explain');if(q.c==='vocab'||q.c==='phrase'){const term=q.o[q.a],meaning=q.c==='vocab'?vocabMeanings[term]:phraseMeanings[term];e.innerHTML='<b>'+(i===correctIndex?'正解！':'正解：'+String.fromCharCode(65+correctIndex)+'. '+meaning)+'</b><br><strong>'+escapeHtml(q.c==='vocab'?term:(phraseDisplay[term]||term))+' = '+escapeHtml(meaning)+'</strong><br><br>📝 例文：'+escapeHtml(fullSentence(q))+'<br>🇯🇵 '+escapeHtml(roughTranslation(q))+'<br><br>📘 '+escapeHtml(q.e);}else{e.innerHTML='<b>'+(i===q.a?'正解！':'正解：'+String.fromCharCode(65+q.a)+'. '+q.o[q.a])+'</b><br><br>🇯🇵 <strong>問題の和訳</strong><br>'+escapeHtml(q.jp||'')+'<br><br>📘 <strong>解説</strong><br>'+escapeHtml(q.e);}e.classList.remove('hidden');document.getElementById('nextBtn').classList.remove('hidden')};
window.startGrammar=function(gc){pool=questions.map((q,i)=>({...q,i})).filter(x=>x.c==='grammar'&&(gc==='all'||x.gc===gc)).sort(()=>Math.random()-.5);pos=0;allHide();document.getElementById('quiz').classList.remove('hidden');renderQuestion();scrollTo(0,0)};
function installGrammarPicker(){const grammarCard=[...document.querySelectorAll('button.card')].find(b=>b.querySelector('h3')?.textContent.includes('文法問題'));if(!grammarCard)return;grammarCard.onclick=null;grammarCard.addEventListener('click',()=>{const old=document.getElementById('grammarPicker');if(old)old.remove();const cats=['all','時制','前置詞','品詞','接続詞','分詞','関係詞','受動態','比較','主語と動詞の一致','語法'];const p=document.createElement('div');p.id='grammarPicker';p.className='card';p.style.marginTop='14px';p.innerHTML='<h3>✏️ 文法カテゴリを選択</h3><p style="margin-bottom:12px">苦手分野だけでも、全カテゴリからでも演習できます。</p><div class="btnrow">'+cats.map(c=>'<button class="btn '+(c==='all'?'primary':'')+'" data-gc="'+c+'">'+(c==='all'?'🎯 全カテゴリ':c)+'</button>').join('')+'</div>';grammarCard.parentElement.after(p);p.querySelectorAll('[data-gc]').forEach(b=>b.onclick=()=>startGrammar(b.dataset.gc));p.scrollIntoView({behavior:'smooth',block:'center'});});}
const ver=document.querySelector('.ver');if(ver)ver.textContent='ver 1.1.0';
const vocabCard=[...document.querySelectorAll('button.card')].find(b=>b.querySelector('h3')?.textContent.includes('単語問題'));if(vocabCard)vocabCard.querySelector('p').textContent='英単語だけを見て日本語の意味を4択。解答後に例文を確認。';
const phraseCard=[...document.querySelectorAll('button.card')].find(b=>b.querySelector('h3')?.textContent.includes('熟語問題'));if(phraseCard)phraseCard.querySelector('p').textContent='英熟語だけを見て日本語の意味を4択。解答後に例文を確認。';
const grammarCard=[...document.querySelectorAll('button.card')].find(b=>b.querySelector('h3')?.textContent.includes('文法問題'));if(grammarCard)grammarCard.querySelector('p').textContent='TOEIC Part 5風の穴埋め問題。カテゴリ別演習と解答後の和訳・解説に対応。';
installGrammarPicker();
})();