(()=>{
const vMean=['拡大する','守る・順守する','確認する・見直す','無料の','発表する','大幅に・著しく','迅速な','能力・収容力','提出する','効率','位置している','歩合・手数料','払い戻す','有効な','予定','特定する','品揃え・選択肢','承認','適任の・資格のある','中断','包括的な','証明','生み出す','必須の','収容する・対応する','評判','到着する','選択肢','改装','声明・発表'];
const pMean=['～が原因で','遅くとも～までに','発効する','～を担当して','～のために・～が原因で','～以内に','連絡を楽しみにする','急な通知で','事前承認を得て','～の場合に備えて','～から徒歩圏内に','～を代表して・～に代わって','定期的に','～している途中で','～を受ける・～を条件とする','無料で','～に賛成して','前もって','別途通知があるまで','通常使用の条件下で'];
const pDisplay=['due to','no later than','go into effect','in charge of','because of','within 30 days','look forward to hearing','at short notice','with prior approval','in case','within walking distance of','on behalf of','on a regular basis','in the process of','be subject to','free of charge','in favor of','in advance','until further notice','under normal use'];
questions.filter(q=>q.c==='vocab').slice(0,30).forEach((q,i)=>q.meaning=vMean[i]);
questions.filter(q=>q.c==='phrase').slice(0,20).forEach((q,i)=>{q.meaning=pMean[i];q.display=pDisplay[i]});
const shuffled=a=>[...a].sort(()=>Math.random()-.5);
const term=q=>q.o[q.a];
const shown=q=>q.c==='phrase'?(q.display||term(q)):term(q);
const meanings=c=>[...new Set(questions.filter(q=>q.c===c&&q.meaning).map(q=>q.meaning))];
function choiceMeanings(q){const rest=shuffled(meanings(q.c).filter(x=>x!==q.meaning)).slice(0,3);return shuffled([q.meaning,...rest])}
function scrollQuiz(){const el=document.getElementById('quiz');if(el&&!el.classList.contains('hidden'))requestAnimationFrame(()=>el.scrollIntoView({behavior:'smooth',block:'start'}))}
window.renderQuestion=function(){locked=false;const q=pool[pos];if(!q){showHome();return}document.getElementById('qcat').textContent=q.c==='grammar'?'文法・'+(q.gc||'総合'):labels[q.c]+'問題';document.getElementById('qnum').textContent=(pos+1)+' / '+pool.length;const qt=document.getElementById('qtext'),box=document.getElementById('choices');box.innerHTML='';if(q.c==='vocab'||q.c==='phrase'){qt.textContent=shown(q);q._meanOpts=choiceMeanings(q);q._correct=q._meanOpts.indexOf(q.meaning);q._meanOpts.forEach((x,i)=>{const b=document.createElement('button');b.className='choice';b.textContent=String.fromCharCode(65+i)+'. '+x;b.onclick=()=>answer(i,b);box.appendChild(b)})}else{qt.textContent=q.q;q.o.forEach((x,i)=>{const b=document.createElement('button');b.className='choice';b.textContent=String.fromCharCode(65+i)+'. '+x;b.onclick=()=>answer(i,b);box.appendChild(b)})}document.getElementById('explain').classList.add('hidden');document.getElementById('nextBtn').classList.add('hidden')};
window.answer=function(i,b){if(locked)return;locked=true;const q=pool[pos],correct=(q.c==='vocab'||q.c==='phrase')?q._correct:q.a,buttons=[...document.querySelectorAll('.choice')];buttons[correct]?.classList.add('correct');if(i!==correct)b.classList.add('wrong');state.history[q.i]=i===correct;save();const e=document.getElementById('explain');if(q.c==='vocab'||q.c==='phrase'){const sentence=q.q.replace('_____',term(q));e.innerHTML='<b>'+(i===correct?'正解！':'正解：'+String.fromCharCode(65+correct)+'. '+escapeHtml(q.meaning))+'</b><br><strong>'+escapeHtml(shown(q))+' = '+escapeHtml(q.meaning)+'</strong><br><br>📝 例文：'+escapeHtml(sentence)+'<br><br>📘 '+escapeHtml(q.e)}else{e.innerHTML='<b>'+(i===q.a?'正解！':'正解：'+String.fromCharCode(65+q.a)+'. '+escapeHtml(q.o[q.a]))+'</b><br><br>🇯🇵 <strong>問題の和訳</strong><br>'+escapeHtml(q.jp||'')+'<br><br>📘 <strong>解説</strong><br>'+escapeHtml(q.e)}e.classList.remove('hidden');document.getElementById('nextBtn').classList.remove('hidden')};
window.renderList=function(){const cat=document.getElementById('listCat').value,s=document.getElementById('listSearch').value.toLowerCase(),body=document.getElementById('listBody');body.innerHTML='';questions.forEach((q,i)=>{if(cat!=='all'&&q.c!==cat)return;const text=q.c==='grammar'?q.q:shown(q),ans=q.c==='grammar'?String.fromCharCode(65+q.a)+'. '+q.o[q.a]:q.meaning,category=q.c==='grammar'?'文法・'+(q.gc||'総合'):labels[q.c],search=[text,ans,q.q,q.o.join(' '),q.e,q.jp||'',q.gc||''].join(' ').toLowerCase();if(s&&!search.includes(s))return;const h=state.history[i],status=h===true?'<span class="ok">○ 正解</span>':h===false?'<span class="ng">× 復習</span>':'<span class="none">未回答</span>',tr=document.createElement('tr');tr.innerHTML='<td>'+(i+1)+'</td><td>'+escapeHtml(category)+'</td><td><strong>'+escapeHtml(text)+'</strong>'+(q.c==='grammar'&&q.jp?'<br><span class="none">'+escapeHtml(q.jp)+'</span>':'')+'</td><td>'+escapeHtml(ans||'')+'</td><td>'+status+'</td>';body.appendChild(tr)})};
function launch(items,count){let xs=shuffled(items);if(count!=='all')xs=xs.slice(0,Math.min(Number(count),xs.length));pool=xs;pos=0;allHide();document.getElementById('quiz').classList.remove('hidden');renderQuestion();scrollQuiz()}
function removeSetup(){document.getElementById('quizSetup')?.remove()}
function styles(){if(document.getElementById('toeicSetupStyles'))return;const s=document.createElement('style');s.id='toeicSetupStyles';s.textContent='.practice-step{margin-top:20px}.practice-label{font-size:13px;font-weight:900;margin-bottom:10px}.practice-count-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.practice-count{display:block;cursor:pointer}.practice-count input{position:absolute;opacity:0}.practice-count span{display:flex;flex-direction:column;gap:4px;padding:14px 10px;border:1px solid var(--line);border-radius:14px;background:#0b1728;text-align:center}.practice-count input:checked+span{border-color:var(--accent);box-shadow:0 0 0 1px var(--accent) inset}.setup-start{width:100%;font-size:15px;padding:14px;margin-top:16px}.grammar-cat-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-bottom:18px}.grammar-cat{border:1px solid var(--line);border-radius:13px;padding:12px;background:#0b1728;color:var(--text);font-weight:800;cursor:pointer;text-align:left}.grammar-cat.active{border-color:var(--accent)}@media(max-width:520px){.practice-count-grid,.grammar-cat-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
function counts(){return '<div class="practice-step"><div class="practice-label">問題数</div><div class="practice-count-grid"><label class="practice-count"><input type="radio" name="practiceCount" value="10" checked><span><strong>10問</strong><small>短時間で演習</small></span></label><label class="practice-count"><input type="radio" name="practiceCount" value="20"><span><strong>20問</strong><small>しっかり演習</small></span></label><label class="practice-count"><input type="radio" name="practiceCount" value="all"><span><strong>全問</strong><small>まとめて演習</small></span></label></div></div>'}
function shell(title,desc,body){styles();removeSetup();allHide();const p=document.createElement('section');p.id='quizSetup';p.className='card';p.style.maxWidth='760px';p.style.margin='22px auto';p.innerHTML='<div class="qmeta"><span>演習設定</span><span>ORIVECTOR TOEIC / 全1000問</span></div><h2 style="margin:12px 0 8px">'+title+'</h2><p style="color:var(--muted);line-height:1.7">'+desc+'</p>'+body+'<button class="btn ghost next" id="setupBack">ホームに戻る</button>';document.querySelector('main.wrap').prepend(p);p.querySelector('#setupBack').onclick=()=>{p.remove();showHome()};requestAnimationFrame(()=>p.scrollIntoView({behavior:'smooth',block:'start'}));return p}
function openSimple(cat){const items=questions.map((q,i)=>({...q,i})).filter(x=>x.c===cat),title=cat==='vocab'?'🔤 単語問題':'🧩 熟語問題',p=shell(title,'全'+items.length+'問から問題数を選んでください。',counts()+'<button class="btn primary setup-start" id="setupStart">この設定で開始</button>');p.querySelector('#setupStart').onclick=()=>{const n=p.querySelector('input[name="practiceCount"]:checked').value;p.remove();launch(items,n)}}
function openGrammar(){const cats=['all','時制','前置詞','品詞','接続詞','分詞','関係詞','受動態','比較','主語と動詞の一致','語法'],body='<div class="practice-label">① カテゴリ</div><div class="grammar-cat-grid">'+cats.map(c=>'<button class="grammar-cat '+(c==='all'?'active':'')+'" data-gc="'+c+'">'+(c==='all'?'全カテゴリ':c)+'</button>').join('')+'</div><div class="practice-label">② 問題数</div>'+counts()+'<button class="btn primary setup-start" id="setupStart">この設定で開始</button>',p=shell('✏️ 文法問題','全550問。カテゴリと問題数を選んでください。',body);let selected='all';p.querySelectorAll('[data-gc]').forEach(b=>b.onclick=()=>{selected=b.dataset.gc;p.querySelectorAll('[data-gc]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});p.querySelector('#setupStart').onclick=()=>{const n=p.querySelector('input[name="practiceCount"]:checked').value,items=questions.map((q,i)=>({...q,i})).filter(x=>x.c==='grammar'&&(selected==='all'||x.gc===selected));p.remove();launch(items,n)}}
window.startQuiz=cat=>cat==='grammar'?openGrammar():openSimple(cat);window.startGrammar=openGrammar;
const oldNext=window.nextQuestion;if(oldNext)window.nextQuestion=function(){oldNext();scrollQuiz()};const oldWrong=window.startWrong;if(oldWrong)window.startWrong=function(){oldWrong();scrollQuiz()};
const cards=[...document.querySelectorAll('button.card')];const vc=cards.find(b=>b.querySelector('h3')?.textContent.includes('単語問題'));if(vc){vc.onclick=()=>openSimple('vocab');vc.querySelector('p').textContent='全300問。英単語から日本語の意味を4択で反復。'}const pc=cards.find(b=>b.querySelector('h3')?.textContent.includes('熟語問題'));if(pc){pc.onclick=()=>openSimple('phrase');pc.querySelector('p').textContent='全150問。頻出熟語・定型表現を4択で反復。'}const gc=cards.find(b=>b.querySelector('h3')?.textContent.includes('文法問題'));if(gc){const fresh=gc.cloneNode(true);gc.replaceWith(fresh);fresh.onclick=openGrammar;fresh.querySelector('p').textContent='全550問。Part 5風文法をカテゴリ別に演習。'}
const badge=document.querySelector('#home .badge');if(badge)badge.textContent='ORIVECTOR ORIGINAL / 全1000問';const ver=document.querySelector('.ver');if(ver)ver.textContent='ver 1.4.0';
console.log('ORIVECTOR TOEIC bank:',questions.length,'questions');if(questions.length!==1000)console.warn('Expected 1000 questions, got',questions.length);
const mode=new URLSearchParams(location.search).get('mode');if(mode)setTimeout(()=>{if(['vocab','phrase','grammar'].includes(mode))window.startQuiz(mode);else if(mode==='wrong')window.startWrong?.();else if(mode==='list')window.showList?.()},0);
})();