(()=>{
function shuffled(items){return [...items].sort(()=>Math.random()-.5)}
function launch(items,count){let xs=shuffled(items);if(count!=='all')xs=xs.slice(0,Math.min(Number(count),xs.length));pool=xs;pos=0;allHide();document.getElementById('quiz').classList.remove('hidden');renderQuestion();scrollTo(0,0)}
function removeSetup(){document.getElementById('quizSetup')?.remove()}
function installSetupStyles(){if(document.getElementById('toeicSetupStyles'))return;const s=document.createElement('style');s.id='toeicSetupStyles';s.textContent='.practice-step{margin-top:20px}.practice-label{font-size:13px;font-weight:900;margin-bottom:10px}.practice-count-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.practice-count{display:block;cursor:pointer}.practice-count input{position:absolute;opacity:0;pointer-events:none}.practice-count span{display:flex;flex-direction:column;gap:4px;padding:14px 10px;border:1px solid var(--line);border-radius:14px;background:#0b1728;text-align:center;transition:.18s}.practice-count strong{font-size:17px}.practice-count small{font-size:11px;color:var(--muted)}.practice-count input:checked+span{border-color:var(--accent);background:linear-gradient(180deg,rgba(124,156,255,.14),#0b1728);box-shadow:0 0 0 1px rgba(124,156,255,.18) inset}.practice-count input:focus-visible+span{outline:2px solid var(--accent);outline-offset:3px}.setup-start{width:100%;font-size:15px;padding:14px;margin-top:16px}.grammar-cat-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-bottom:18px}.grammar-cat{border:1px solid var(--line);border-radius:13px;padding:12px;background:#0b1728;color:var(--text);font-weight:800;cursor:pointer;text-align:left}.grammar-cat.active{border-color:var(--accent);background:linear-gradient(180deg,rgba(124,156,255,.14),#0b1728)}@media(max-width:520px){.practice-count-grid{grid-template-columns:1fr}.practice-count span{flex-direction:row;justify-content:space-between;align-items:center;text-align:left}.grammar-cat-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
function setupShell(title,description,body){installSetupStyles();removeSetup();allHide();const p=document.createElement('section');p.id='quizSetup';p.className='card';p.style.maxWidth='760px';p.style.margin='22px auto';p.innerHTML='<div class="qmeta"><span>演習設定</span><span>ORIVECTOR TOEIC</span></div><h2 style="margin:12px 0 8px">'+title+'</h2><p style="color:var(--muted);line-height:1.7;margin:0 0 18px">'+description+'</p>'+body+'<button class="btn ghost next" id="setupBack">ホームに戻る</button>';document.querySelector('main.wrap').prepend(p);document.getElementById('setupBack').onclick=()=>{p.remove();showHome()};scrollTo(0,0);return p}
function countSelector(){return '<div class="practice-step"><div class="practice-label">問題数</div><div class="practice-count-grid"><label class="practice-count"><input type="radio" name="practiceCount" value="10" checked><span><strong>10問</strong><small>短時間で演習</small></span></label><label class="practice-count"><input type="radio" name="practiceCount" value="20"><span><strong>20問</strong><small>しっかり演習</small></span></label><label class="practice-count"><input type="radio" name="practiceCount" value="all"><span><strong>全問</strong><small>まとめて演習</small></span></label></div></div>'}
function openSimpleSetup(cat){const items=questions.map((q,i)=>({...q,i})).filter(x=>x.c===cat);const title=cat==='vocab'?'🔤 単語問題':cat==='phrase'?'🧩 熟語問題':labels[cat]+'問題';const p=setupShell(title,'演習する問題数を選んでください。',countSelector()+'<button class="btn primary setup-start" id="setupStart">この設定で開始</button>');p.querySelector('#setupStart').onclick=()=>{const n=p.querySelector('input[name="practiceCount"]:checked').value;p.remove();launch(items,n)}}
function openGrammarSetup(){const cats=['all','時制','前置詞','品詞','接続詞','分詞','関係詞','受動態','比較','主語と動詞の一致','語法'];const body='<div class="practice-step"><div class="practice-label">① カテゴリ</div><div class="grammar-cat-grid" id="grammarCats">'+cats.map(c=>'<button class="grammar-cat '+(c==='all'?'active':'')+'" data-gc="'+c+'">'+(c==='all'?'全カテゴリ':c)+'</button>').join('')+'</div></div><div class="practice-label">② 問題数</div>'+countSelector()+'<button class="btn primary setup-start" id="setupStart">この設定で開始</button>';const p=setupShell('✏️ 文法問題','カテゴリと問題数を選んでから演習を開始します。',body);let selected='all';p.querySelectorAll('[data-gc]').forEach(b=>b.onclick=()=>{selected=b.dataset.gc;p.querySelectorAll('[data-gc]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});p.querySelector('#setupStart').onclick=()=>{const n=p.querySelector('input[name="practiceCount"]:checked').value;const items=questions.map((q,i)=>({...q,i})).filter(x=>x.c==='grammar'&&(selected==='all'||x.gc===selected));p.remove();launch(items,n)}}
window.startQuiz=function(cat){if(cat==='grammar')openGrammarSetup();else openSimpleSetup(cat)};
window.startGrammar=function(){openGrammarSetup()};
const grammarCard=[...document.querySelectorAll('button.card')].find(b=>b.querySelector('h3')?.textContent.includes('文法問題'));if(grammarCard){const fresh=grammarCard.cloneNode(true);grammarCard.replaceWith(fresh);fresh.onclick=()=>openGrammarSetup()}
const vocabCard=[...document.querySelectorAll('button.card')].find(b=>b.querySelector('h3')?.textContent.includes('単語問題'));if(vocabCard)vocabCard.onclick=()=>openSimpleSetup('vocab');
const phraseCard=[...document.querySelectorAll('button.card')].find(b=>b.querySelector('h3')?.textContent.includes('熟語問題'));if(phraseCard)phraseCard.onclick=()=>openSimpleSetup('phrase');
const ver=document.querySelector('.ver');if(ver)ver.textContent='ver 1.3.1';
})();